---
permalink: storage/task_data_protection_create_a_snapshot_schedule.html 
sidebar: sidebar 
keywords: snapshot schedule, create, volumes, recurring schedule 
summary: Sie können einen Snapshot eines Volumes oder Volumes so planen, dass er automatisch in bestimmten Intervallen erfolgt. 
---
= Erstellen eines Snapshot-Zeitplans
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können einen Snapshot eines Volumes oder Volumes so planen, dass er automatisch in bestimmten Intervallen erfolgt.

Wenn Sie einen Snapshot-Zeitplan konfigurieren, können Sie zwischen verschiedenen Zeitabständen wählen, die auf Wochentagen oder Tagen des Monats basieren. Sie können auch einen wiederkehrenden Zeitplan erstellen und die Tage, Stunden und Minuten vor dem nächsten Snapshot festlegen.

Wenn Sie einen Snapshot für einen Zeitraum planen, der nicht durch 5 Minuten teilbar ist, wird der Snapshot zum nächsten Zeitraum ausgeführt, der durch 5 Minuten teilbar ist. Wenn Sie beispielsweise einen Snapshot für die Ausführung um 12:42:00 UTC planen, wird dieser um 12:45:00 UTC ausgeführt. Ein Snapshot kann nicht in Intervallen von weniger als 5 Minuten ausgeführt werden.

.Schritte
. Klicken Sie Auf *Datenschutz* > *Termine*.
. Klicken Sie Auf *Zeitplan Erstellen*.
. Geben Sie im Feld *Volume IDs CSV* eine einzelne Volume-ID oder eine kommagetrennte Liste von Volume-IDs ein, die in den Snapshot-Vorgang aufgenommen werden sollen.
. Geben Sie einen neuen Planungsnamen ein.
. Wählen Sie einen Zeitplantyp aus, und legen Sie den Zeitplan aus den verfügbaren Optionen fest.
. *Optional:* Wählen Sie *wiederkehrender Zeitplan*, um den Snapshot-Zeitplan auf unbestimmte Zeit zu wiederholen.
. *Optional:* Geben Sie im Feld *New Snapshot Name* einen Namen für den neuen Snapshot ein.
+
Wenn Sie das Feld leer lassen, verwendet das System die Uhrzeit und das Datum der Erstellung des Snapshots als Namen.

. *Optional:* Aktivieren Sie das Kontrollkästchen *Snapshots in Replikation einschließen bei gepaarten*, um sicherzustellen, dass die Snapshots bei der Replikation erfasst werden, wenn das übergeordnete Volume gekoppelt ist.
. Um die Aufbewahrung für den Snapshot festzulegen, wählen Sie eine der folgenden Optionen aus:
+
** Klicken Sie auf *Keep Forever*, um den Snapshot auf dem System auf unbestimmte Zeit zu behalten.
** Klicken Sie auf *Aufbewahrungszeitraum festlegen* und verwenden Sie die Datumspinnboxen, um eine Zeitdauer für das System auszuwählen, um den Snapshot zu behalten.


. Klicken Sie Auf *Zeitplan Erstellen*.

